theme: jekyll-theme-slate
github:
    repository_name: karton
    repository_url: http://github.com/karton/karton
    owner_name: Marco Barisione
    owner_url: http://www.barisione.org/
title: Karton
description: Run Linux programs on macOS or on a different Linux distribution
google_analytics: UA-92189187-1
navbar_pages:
    - url: /
      title: Home
    - url: /install.html
      title: Install
    - url: /how-to-use.html
      title: How to use
    - url: /faq.html
      title: FAQ
    - url: /contribute.html
      title: Contribute
